"""SNOMED milestone B: RF2 pipeline + DAG semantics on the synthetic
fixture (design snomed-module.md §4, §6, §9) — license-clean, offline.

The fixture is a fabricated mini clinical world; these tests prove the
loader (active filtering, preferred terms, semantic tags), the closure
(multi-parent DAG, min_depth), the OntologyService on a DAG, attribute
edges (the thrombectomy shape), and the protocol dispatch that milestone
A prepared."""

import sys
from pathlib import Path

import pytest
from sqlalchemy import select

from hdh.core.models import get_engine, get_session
from hdh.core.ontology import get_ontology_service
from hdh.core.schema_registry import bootstrap_schema
from hdh.modules.snomed.loader import LoadError, run_load
from hdh.modules.snomed.loader.rf2 import ROOT_CONCEPT, is_valid_sctid

FIXTURES = Path(__file__).parent / "fixtures" / "snomed"
sys.path.insert(0, str(FIXTURES))
import fixture_ids as fx  # noqa: E402  (generated by make_fixture.py)


@pytest.fixture(scope="module")
def catalog(tmp_path_factory):
    """The synthetic RF2 fixture, loaded once for all milestone-B tests."""
    bootstrap_schema()
    db = tmp_path_factory.mktemp("snomed") / "catalog.db"
    engine = get_engine(str(db))
    session = get_session(engine)
    report = run_load(session, FIXTURES)
    session.info["report"] = dict(report)
    yield session
    session.close()
    engine.dispose()


@pytest.fixture(scope="module")
def service(catalog):
    return get_ontology_service("snomed_ct", catalog)


def test_pipeline_runs_all_stages(catalog):
    report = catalog.info["report"]
    assert list(report) == [
        "acquire",
        "parse",
        "build",
        "load",
        "closure",
        "accelerate",
        "verify",
        "finalize",
    ]
    assert "release 202603" in report["acquire"]
    assert "root present" in report["verify"]


def test_fixture_sctids_are_structurally_valid():
    assert is_valid_sctid(fx.BLORBITIS)
    assert is_valid_sctid(ROOT_CONCEPT)
    assert not is_valid_sctid("123")  # too short
    assert not is_valid_sctid(fx.BLORBITIS[:-1] + "0")  # broken check digit


def test_inactive_concept_and_relationship_excluded(catalog, service):
    """Glimmerpox is inactive; the retired is-a row must not create edges."""
    assert service.lookup(fx.RETIRED) is None
    assert not service.subsumes(fx.CHRONIC_BLORBITIS, fx.SEVERE_ACUTE)  # inactive rel ignored


def test_preferred_term_and_semantic_tag(service):
    concept = service.lookup(fx.BLORBITIS)
    assert concept.display == "Blorbitis"  # preferred term, not FSN
    assert concept.properties["fsn"] == "Blorbitis (disorder)"
    assert concept.properties["semantic_tag"] == "disorder"
    assert concept.kind == "concept"


def test_dag_multi_parent_ancestors(service):
    """Blorbitis of flenum has TWO parents — both chains must appear."""
    codes = {c.code for c in service.ancestors(fx.FLENUM_BLORBITIS)}
    assert {fx.BLORBITIS, fx.DISORDER_FLENUM, ROOT_CONCEPT} <= codes


def test_descendant_sweep_and_min_depth(catalog, service):
    codes = {c.code for c in service.descendants(fx.BLORBITIS)}
    assert {fx.ACUTE_BLORBITIS, fx.CHRONIC_BLORBITIS, fx.SEVERE_ACUTE, fx.FLENUM_BLORBITIS} <= codes
    from hdh.core.models import Base

    closure_t = Base.metadata.tables["ontology_closure"]
    depth = catalog.execute(
        select(closure_t.c.min_depth).where(
            closure_t.c.ancestor_id == f"snomed_ct:{fx.BLORBITIS}",
            closure_t.c.descendant_id == f"snomed_ct:{fx.SEVERE_ACUTE}",
        )
    ).scalar()
    assert depth == 2  # Blorbitis -> Acute -> Severe acute


def test_subsumes_is_one_closure_hit(service):
    assert service.subsumes(fx.BLORBITIS, fx.SEVERE_ACUTE)
    assert service.subsumes(ROOT_CONCEPT, fx.FLENUMECTOMY)
    assert not service.subsumes(fx.SEVERE_ACUTE, fx.BLORBITIS)  # direction matters
    assert not service.subsumes(fx.BLORBITIS, fx.BLORBITIS)  # strict


def test_synonyms_preferred_first(service):
    terms = service.synonyms(fx.BLORBITIS)
    assert terms[0] == "Blorbitis"
    assert "Blorb inflammation" in terms and "Glimmer fever" in terms
    assert "Blorbitis (disorder)" in terms  # the FSN rides along


def test_normalize_finds_by_synonym(service):
    candidates = service.normalize("glimmer fever")
    assert candidates and candidates[0].concept.code == fx.BLORBITIS
    assert candidates[0].score >= 0.95  # exact term match (term type only tiebreaks)
    assert "Glimmer fever" in candidates[0].reason


def test_attribute_edges_carry_intervention_semantics(service):
    """The thrombectomy shape: method → Removal, site → Flenum structure."""
    grouped = service.attributes(fx.FLENUMECTOMY)
    assert {c.code for c in grouped["method"]} == {fx.REMOVAL_ACTION}
    assert {c.code for c in grouped["procedure_site_direct"]} == {fx.FLENUM_STRUCT}
    finding = service.attributes(fx.FLENUM_BLORBITIS)
    assert {c.code for c in finding["finding_site"]} == {fx.FLENUM_STRUCT}


def test_path_stays_null_for_dag_rows(catalog):
    """§3: tree conveniences are ICD-private; DAG rows carry NULL path."""
    from hdh.core.models import Base

    concepts_t = Base.metadata.tables["ontology_concepts"]
    row = catalog.execute(
        select(concepts_t.c.path, concepts_t.c.hierarchy_depth).where(
            concepts_t.c.id == f"snomed_ct:{fx.BLORBITIS}"
        )
    ).first()
    assert row.path is None and row.hierarchy_depth is None


def test_reload_requires_force_and_force_replaces(catalog):
    with pytest.raises(LoadError, match="--force"):
        run_load(catalog, FIXTURES)
    report = dict(run_load(catalog, FIXTURES, force=True))
    assert "concepts" in report["load"]
    service = get_ontology_service("snomed_ct", catalog)
    assert service.lookup(fx.BLORBITIS) is not None  # catalog intact after replace


def test_ledger_records_the_release(catalog):
    from hdh.core.models import Base

    loads_t = Base.metadata.tables["ontology_loads"]
    rows = catalog.execute(select(loads_t).where(loads_t.c.ontology == "snomed_ct")).all()
    assert rows and all(row.fiscal_year == 202603 for row in rows)
    assert rows[-1].properties["closure_rows"] > 0
