"""Baseline: the registry-merged schema as of v0.2.

This revision is intentionally empty. Databases created before Alembic
arrived already hold the full schema from ``Base.metadata.create_all()``;
mark them as current with ``just db-stamp`` (``alembic stamp head``).
Fresh databases get their schema from ``create_all`` too, then stamp.
Every schema change after this point ships as an autogenerated revision
(``just db-revision "module: what changed"``).

Revision ID: 0001
Revises:
Create Date: 2026-08-10
"""

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
