"""Reconcile stamped databases with the registry-merged metadata (issue #30).

The chart expansion (v0.4.0) added columns to pre-existing tables without
shipping a revision. Databases stamped with ``alembic_version`` disable
the registry's auto-ADD fallback (by design), so those columns were
silently missing — a real dev PostgreSQL hit INSERT failures on
``patients.marital_status``.

This revision closes the gap the durable way: an **inspector-guarded,
add-only reconciliation** against the current registry-merged metadata
(env.py bootstraps the registry, so module extension columns are
included). It is idempotent and correct from ANY stamped drift state —
databases that already carry the columns get a no-op. Missing tables are
not created here; ``get_engine``'s ``create_all`` owns table creation.

The boundary, stated once: pre-Alembic databases get missing columns
auto-added by ``ensure_columns``; stamped databases get them by running
``just db-upgrade`` (this revision). Every schema change from now on
ships its own autogenerated revision (``just db-revision "msg"``).

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-15
"""

from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Add every metadata column missing from the connected database."""
    from hdh.core.schema_registry import reconcile_missing_columns

    added = reconcile_missing_columns(op.get_bind())
    if added:
        print(f"   reconciled {len(added)} missing columns: {', '.join(added)}")


def downgrade() -> None:
    """Not reversed: reconciled columns may hold data, and which columns
    were added depends on the database's prior drift state."""
